-- DALAB INTERNET — PostgreSQL schema
-- Direct translation of the proven SQLite schema (dalab-backend.zip), with
-- the dialect differences noted inline. This is the source of truth for
-- Postgres; run via `npm run migrate` (see src/db/migrate.ts).

CREATE EXTENSION IF NOT EXISTS "pgcrypto"; -- gen_random_uuid()

CREATE TABLE IF NOT EXISTS admin_users (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role          TEXT NOT NULL DEFAULT 'super_admin' CHECK (role IN ('super_admin','admin')),
  last_login_at TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS admin_password_resets (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id      UUID NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  token_hash    TEXT NOT NULL,
  expires_at    TIMESTAMPTZ NOT NULL,
  consumed      BOOLEAN NOT NULL DEFAULT false,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_admin_password_resets_admin_id ON admin_password_resets(admin_id);

CREATE TABLE IF NOT EXISTS companies (
  id                    TEXT PRIMARY KEY,   -- short slug id, e.g. "hormuud"
  name                  TEXT NOT NULL,
  group_number          INTEGER NOT NULL CHECK (group_number IN (1,2)),
  color_hex             TEXT NOT NULL,
  logo_url              TEXT,
  status                TEXT NOT NULL DEFAULT 'online' CHECK (status IN ('online','offline')),
  gateway               TEXT,
  payment_number        TEXT,
  payment_ussd_template TEXT,
  ussd_code             TEXT,
  pin_encrypted         TEXT,               -- AES-256-GCM ciphertext — see src/auth/crypto.ts
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS packages (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id    TEXT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  category_id   TEXT NOT NULL,
  name          TEXT NOT NULL,
  old_price     NUMERIC(10,2),
  price         NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  mb            INTEGER NOT NULL DEFAULT 0,
  minutes       INTEGER NOT NULL DEFAULT 0,
  sms           INTEGER NOT NULL DEFAULT 0,
  validity      TEXT,
  active        BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_packages_company_id ON packages(company_id);

CREATE TABLE IF NOT EXISTS customers (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone          TEXT NOT NULL UNIQUE,
  name           TEXT,
  status         TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','blocked')),
  macaash_points INTEGER NOT NULL DEFAULT 0,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS otp_codes (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone       TEXT NOT NULL,
  code_hash   TEXT NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  consumed    BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_otp_codes_phone ON otp_codes(phone);
CREATE INDEX IF NOT EXISTS idx_otp_codes_expires_at ON otp_codes(expires_at);

CREATE TABLE IF NOT EXISTS agents (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone         TEXT NOT NULL UNIQUE,
  name          TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended')),
  device_id     TEXT,
  last_login_at TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agent_devices (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sim_routing (
  company_id  TEXT PRIMARY KEY REFERENCES companies(id) ON DELETE CASCADE,
  device_id   TEXT REFERENCES agent_devices(id) ON DELETE SET NULL,
  sim_slot    INTEGER NOT NULL CHECK (sim_slot IN (1,2)),
  updated_by  UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id              TEXT PRIMARY KEY,   -- "DLB..." reference, generated by the app not the DB
  customer_id     UUID NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  company_id      TEXT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  package_id      UUID NOT NULL REFERENCES packages(id) ON DELETE RESTRICT,
  amount          NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
  status          TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','in_progress','completed','failed','cancelled')),
  sender_phone    TEXT,
  receiver_phone  TEXT,
  payment_method  TEXT,
  gateway_ref     TEXT,
  channel         TEXT,
  macaash_earned  INTEGER NOT NULL DEFAULT 0,
  agent_id        UUID REFERENCES agents(id) ON DELETE SET NULL,
  ussd_generated  TEXT,
  completed_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_company_id  ON orders(company_id);
CREATE INDEX IF NOT EXISTS idx_orders_status      ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_agent_id    ON orders(agent_id);
CREATE INDEX IF NOT EXISTS idx_orders_sender_phone   ON orders(sender_phone);
CREATE INDEX IF NOT EXISTS idx_orders_receiver_phone ON orders(receiver_phone);

-- Every payment confirmation SMS an agent's device uploads, matched or not —
-- the "SMS logs" module the spec asks for.
CREATE TABLE IF NOT EXISTS sms_logs (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id          UUID REFERENCES agents(id) ON DELETE SET NULL,
  sender            TEXT NOT NULL,
  body              TEXT NOT NULL,
  parsed_provider   TEXT,
  parsed_amount     NUMERIC(10,2),
  parsed_phone      TEXT,
  matched_order_id  TEXT REFERENCES orders(id) ON DELETE SET NULL,
  received_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sms_logs_agent_id ON sms_logs(agent_id);
CREATE INDEX IF NOT EXISTS idx_sms_logs_matched_order ON sms_logs(matched_order_id);

CREATE TABLE IF NOT EXISTS macaash_transactions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id   UUID NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  order_id      TEXT REFERENCES orders(id) ON DELETE SET NULL,
  points        INTEGER NOT NULL,
  reason        TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_macaash_tx_customer_id ON macaash_transactions(customer_id);

CREATE TABLE IF NOT EXISTS ussd_templates (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id    TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  service_name  TEXT NOT NULL,
  ussd_code     TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'enabled' CHECK (status IN ('enabled','disabled')),
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ussd_templates_company_id ON ussd_templates(company_id);

CREATE TABLE IF NOT EXISTS ussd_logs (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id          TEXT REFERENCES orders(id) ON DELETE SET NULL,
  template_id       UUID REFERENCES ussd_templates(id) ON DELETE SET NULL,
  company_id        TEXT REFERENCES companies(id) ON DELETE SET NULL,
  admin_id          UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  generated_string  TEXT NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ussd_logs_order_id ON ussd_logs(order_id);

CREATE TABLE IF NOT EXISTS ussd_dial_attempts (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id          TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  agent_id          UUID REFERENCES agents(id) ON DELETE SET NULL,
  sim_slot          INTEGER,
  ussd_string       TEXT NOT NULL,
  attempt_number    INTEGER NOT NULL DEFAULT 1,
  status            TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','success','failed')),
  response_message  TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ussd_dial_attempts_order_id ON ussd_dial_attempts(order_id);

CREATE TABLE IF NOT EXISTS banners (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title              TEXT NOT NULL,
  subtitle           TEXT,
  gradient           TEXT,
  target_company_id  TEXT REFERENCES companies(id) ON DELETE SET NULL,
  active             BOOLEAN NOT NULL DEFAULT true,
  position           INTEGER NOT NULL DEFAULT 0,
  start_date         DATE,
  end_date           DATE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_banners_active ON banners(active, position);

CREATE TABLE IF NOT EXISTS notifications (
  id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type      TEXT NOT NULL CHECK (type IN ('push','promotion','maintenance')),
  title     TEXT NOT NULL,
  body      TEXT,
  sent_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- System configuration — the "Settings page" the spec asks for. Simple
-- key/value store so new settings don't need a schema migration to add.
CREATE TABLE IF NOT EXISTS system_settings (
  key         TEXT PRIMARY KEY,
  value       TEXT NOT NULL,
  updated_by  UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  subject_id    TEXT NOT NULL,
  subject_role  TEXT NOT NULL CHECK (subject_role IN ('customer','agent','admin','super_admin')),
  token_hash    TEXT NOT NULL,
  revoked       BOOLEAN NOT NULL DEFAULT false,
  expires_at    TIMESTAMPTZ NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_subject ON refresh_tokens(subject_id, subject_role);
